name: flutter_provider
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  http: ^1.2.1
  firebase_crashlytics: ^3.4.9
  firebase_remote_config: ^4.3.8
  firebase_analytics: ^10.8.0
  flutter_riverpod: ^2.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true