// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN1tPcHFi23sPi-TaTBSEb0v4q9SwABxs',
    appId: '1:726166195349:web:fbb54b8868db0790da1f9c',
    messagingSenderId: '726166195349',
    projectId: 'provider-firebase-77408',
    authDomain: 'provider-firebase-77408.firebaseapp.com',
    storageBucket: 'provider-firebase-77408.appspot.com',
    measurementId: 'G-6KLGK0PD8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgCgL7GZqqTwkW9NrpyCjIget6s25zC2A',
    appId: '1:726166195349:android:53280245df422329da1f9c',
    messagingSenderId: '726166195349',
    projectId: 'provider-firebase-77408',
    storageBucket: 'provider-firebase-77408.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiHWX5bzl6FHF_heb18wdvY2Q2yzUHnNw',
    appId: '1:726166195349:ios:f0690234fc09697dda1f9c',
    messagingSenderId: '726166195349',
    projectId: 'provider-firebase-77408',
    storageBucket: 'provider-firebase-77408.appspot.com',
    iosBundleId: 'com.example.flutterProvider',
  );
}
